[tools]
# Languages
node = "24"
python = "3"
# CLI tools
# Black has to be installed from PyPi to support their ARM fallback to pure-python.
"pipx:black" = "25.11.0"
"pipx:codespell" = "2.4.1"
"pipx:isort" = "7.0.0"
"pipx:mypy" = "1.19.0"
"pipx:pre-commit-hooks" = "6.0.0"
"pipx:pycln" = "2.6.0"
"npm:pyright" = "1.1.407"
"npm:renovate" = "41.173.1"
ruff = "0.14.9"
"pipx:sort-all" = "1.3.0"
uv = "0.9.13"
just = "1.43.1"

[settings]
activate_aggressive = true
experimental = true
gpg_verify = true
lockfile = true
not_found_auto_install = false
paranoid = true
plugin_autoupdate_last_check_duration = "0"
go_skip_checksum = true

[settings.python]
compile = false
uv_venv_auto = false
