name: Run tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-v2
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      extra-installs:
        description: "List of extra tools to install using Mise alongside Python (i.e. Rust for builds)"
        default: ""
        required: false
        type: string
      os-versions:
        description: "Json array of the runner OSes to test against"
        default: '["ubuntu-24.04-arm", "macos-latest", "windows-latest"]'
        required: false
        type: string
      python-versions:
        description: "Json array of the Python versions to test against"
        default: '["3.11", "3.12", "3.13"]'
        required: false
        type: string

jobs:
  py-test:
    strategy:
      fail-fast: false
      matrix:
        runner-os: ${{ fromJSON(inputs.os-versions) }}
        python-version: ${{ fromJSON(inputs.python-versions) }}

    runs-on: ${{ matrix.runner-os }}

    steps:
      - name: Run test job
        uses: FasterSpeeding/Piped-actions/.github/actions/just-jobs@5c201b3c5aaa75ce36c2da8c454579c76d14ead8 # 2025.12.17
        env:
          TEST_PYTHON_VERSION: "${{ matrix.python-version }}"
        with:
          extra-installs: "python@${{ matrix.python-version }} uv ${{ inputs.extra-installs }}"
          task-names: test-python-cov

      - name: Create coverage artifacts
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: .coverage.${{ matrix.runner-os }}.${{ matrix.python-version }}
          path: artifacts/.coverage
          include-hidden-files: true
          if-no-files-found: error
          retention-days: 1

  upload-coverage:
    needs: [py-test]
    runs-on: ubuntu-24.04

    permissions:
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Download artifacts
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          pattern: .coverage.*
          merge-multiple: false
          path: ./artifacts/coverage/

      - name: Run combine-coverage job
        uses: FasterSpeeding/Piped-actions/.github/actions/just-jobs@5c201b3c5aaa75ce36c2da8c454579c76d14ead8 # 2025.12.17
        with:
          extra-installs: python uv
          task-names: combine-coverage

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          files: ./artifacts/coverage.xml
          use_oidc: true

      - name: Create coverage artifacts
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: .coverage.combined
          path: |
            artifacts/coverage.xml
            artifacts/coverage_html
          include-hidden-files: true
          if-no-files-found: error
