name: Publish documentation

on:
  workflow_call:
    inputs:
      committer-email:
        description: "The email address to use for doc branch commits"
        default: 120557446+always-on-duty[bot]@users.noreply.github.com
        required: false
        type: string
      committer-username:
        description: "The username address to use for doc branch commits"
        default: always-on-duty[bot]
        required: false
        type: string

jobs:
  publish-docs:
    runs-on: ubuntu-24.04

    steps:
      - name: Run generate-docs job
        uses: FasterSpeeding/Piped-actions/.github/actions/just-jobs@5e113e7306f79012ab52d439cdcdb1487bea66aa # 2025.10.05
        with:
          extra-installs: python uv
          task-names: generate-docs

      - name: Push
        uses: JamesIves/github-pages-deploy-action@9d877eea73427180ae43cf98e8914934fe157a1a # v4.7.6
        with:
          branch: docs
          commit-message: "${{ env.GITHUB_SHA }} docs (${{ github.event.release.tag_name || github.event.ref }})"
          clean-exclude: pr-preview
          folder: ./artifacts/site
          git-config-email: "${{ inputs.committer-email }}"
          git-config-name: "${{ inputs.committer-username }}"
