name: Run Rustfmt

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-v2
  cancel-in-progress: true

on:
  workflow_call:

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - name: Initialise environment with Mise
        uses: FasterSpeeding/Piped-actions/.github/actions/mise-init@5c201b3c5aaa75ce36c2da8c454579c76d14ead8 # 2025.12.17
        with:
          install-args: rust cargo

      - name: Run rustfmt
        shell: bash
        run: cargo fmt

      - name: Check diff file
        uses: FasterSpeeding/Piped-actions/.github/actions/handle-diff-file@5c201b3c5aaa75ce36c2da8c454579c76d14ead8 # 2025.12.17
