name: Upgrade dependency locks

on:
  schedule:
    - cron: "0 12 1 * *"
  workflow_dispatch:

jobs:
  upgrade-deps:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          submodules: "true"

      - name: Install Python
        uses: ./.github/actions/setup-py

      - name: Upgrade dependency locks
        run: nox -s freeze-locks

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@18e469570b1cf0dfc11d60ec121099f8ff3e617a
        with:
          author: "always-on-duty[bot] <120557446+always-on-duty[bot]@users.noreply.github.com>"
          branch: task/upgrade-deps
          commit-message: Upgrade dependency locks
          committer: "always-on-duty[bot] <120557446+always-on-duty[bot]@users.noreply.github.com>"
          title: Upgrade dependency locks
          token: ${{ secrets.ACTIONS_TOKEN || secrets.GITHUB_TOKEN }}
