name: Verify type-completeness

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-v2
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      extra-installs:
        description: "List of extra tools to install using Mise alongside Python (i.e. Rust for builds)"
        default: ""
        required: false
        type: string

jobs:
  verify-types:
    runs-on: ubuntu-24.04

    steps:
      - name: Run verify-types job
        uses: FasterSpeeding/Piped-actions/.github/actions/just-jobs@5c201b3c5aaa75ce36c2da8c454579c76d14ead8 # 2025.12.17
        with:
          extra-installs: "node python npm:pyright ${{ inputs.extra-installs }}"
          task-names: verify-types
